---
development:
  cloud_name: hkvvnklw9
  api_key: '116816497921428'
  api_secret: KClfhmhsTUq7vbE3c5N5pu0hanY
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: hkvvnklw9
  api_key: '116816497921428'
  api_secret: KClfhmhsTUq7vbE3c5N5pu0hanY
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: hkvvnklw9
  api_key: '116816497921428'
  api_secret: KClfhmhsTUq7vbE3c5N5pu0hanY
  enhance_image_tag: true
  static_image_support: false
